package art.gemosdodo.still;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import ai.onnxruntime.*;
import java.io.*;
import java.net.*;
import java.nio.*;
import java.nio.channels.*;
import java.util.*;
import java.util.concurrent.*;
import org.json.JSONObject;

public class MainActivity extends Activity {
 final ExecutorService jobs=Executors.newSingleThreadExecutor();
 TextView status; ProgressBar progress; Button choose,start,save,logs,cancel; Spinner mode; ImageView preview;
 volatile boolean cancelled=false,running=false; volatile OrtSession.RunOptions activeRun; File photo,result; int imageWidth,imageHeight; final String revision="1a426c9ac9394d2490ad4c78f8422c42771042a1";
 final String graph="sharp_web_predictor_fp16.onnx",weights="sharp_web_predictor_fp16.onnx.data";
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(247,247,241));getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);ScrollView scroll=new ScrollView(this);LinearLayout col=new LinearLayout(this);col.setOrientation(LinearLayout.VERTICAL);col.setPadding(dp(24),dp(32),dp(24),dp(24));col.setBackgroundColor(Color.rgb(247,247,241));scroll.addView(col);setContentView(scroll);scroll.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});
 TextView brand=new TextView(this);brand.setText("Gemos Still\n本机生成 · Android 实验版");brand.setTextSize(26);brand.setTextColor(Color.rgb(35,43,33));col.addView(brand);
 TextView intro=new TextView(this);intro.setText("原生推理验证，不上传照片。首次下载约 1.31 GB，建议 Wi-Fi。模型仅限非商业研究。请保持前台；本机生成仍可能受内存或算子兼容性限制。");intro.setTextSize(14);intro.setPadding(0,dp(16),0,dp(16));col.addView(intro);
 preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);col.addView(preview,new LinearLayout.LayoutParams(-1,dp(200)));
 choose=button(col,"1  选择照片",v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,1);});
 mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"CPU · 原生多线程（实验）","系统加速 NNAPI（实验）"}));col.addView(mode);
 start=button(col,"2  下载模型并生成",v->begin());start.setEnabled(false);
 progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(1000);col.addView(progress,new LinearLayout.LayoutParams(-1,dp(16)));status=new TextView(this);status.setTextSize(14);status.setPadding(0,dp(16),0,dp(16));col.addView(status);
 cancel=button(col,"取消",v->{cancelled=true;try{if(activeRun!=null)activeRun.setTerminate(true);}catch(Exception ignored){}report("正在取消，请等待当前原生操作结束…");});cancel.setEnabled(false);
 save=button(col,"保存记忆文件 .still",v->export(2,"application/octet-stream","Gemos-Still.still"));save.setEnabled(false);logs=button(col,"导出诊断日志",v->export(3,"text/plain","Gemos-Still-log.txt"));
 String previous=getPreferences(0).getString("phase","");status.setText(previous.isEmpty()?"等待选择照片": "上次停在："+previous+"\n若曾自动退出，可能是系统回收内存。可导出日志查看。");
 reportLog("App 0.2 pool-fp32; Device "+Build.MANUFACTURER+" "+Build.MODEL+" Android "+Build.VERSION.RELEASE+" maxJavaHeap="+Runtime.getRuntime().maxMemory());
 }
 int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
 Button button(LinearLayout col,String text,View.OnClickListener cb){Button b=new Button(this);b.setText(text);b.setAllCaps(false);col.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));b.setOnClickListener(cb);return b;}
 void export(int request,String mime,String name){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType(mime);i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,request);}
 @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null)return;Uri uri=data.getData();if(req==1){jobs.execute(()->{try{File temp=new File(getFilesDir(),"selected.tmp");try(InputStream in=getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(temp)){byte[] buf=new byte[65536];int n;long count=0;while((n=in.read(buf))!=-1){count+=n;if(count>25*1024*1024)throw new IOException("照片不能超过 25 MB");out.write(buf,0,n);}}
 BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeFile(temp.getPath(),bounds);imageWidth=bounds.outWidth;imageHeight=bounds.outHeight;if(imageWidth<1||imageHeight<1)throw new IOException("无法解码照片，请换 JPG 或 PNG");BitmapFactory.Options opts=new BitmapFactory.Options();while(Math.max(imageWidth,imageHeight)/Math.max(1,opts.inSampleSize)>1536)opts.inSampleSize=opts.inSampleSize==0?2:opts.inSampleSize*2;Bitmap bmp=BitmapFactory.decodeFile(temp.getPath(),opts);if(bmp==null)throw new IOException("图片解码失败");photo=new File(getFilesDir(),"photo.jpg");try(OutputStream out=new FileOutputStream(photo)){bmp.compress(Bitmap.CompressFormat.JPEG,94,out);}Bitmap thumb=Bitmap.createScaledBitmap(bmp,Math.max(1,bmp.getWidth()/3),Math.max(1,bmp.getHeight()/3),true);bmp.recycle();temp.delete();runOnUiThread(()->{preview.setImageBitmap(thumb);start.setEnabled(true);});report("照片已就绪");}catch(Exception e){report("读取失败："+e.getMessage());}});}else{File file=req==2?result:new File(getFilesDir(),"diagnostics.txt");jobs.execute(()->{try(InputStream in=new FileInputStream(file);OutputStream out=getContentResolver().openOutputStream(uri)){byte[] buf=new byte[65536];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);report("已保存到所选位置");}catch(Exception e){report("保存失败："+e.getMessage());}});}}
 void reportLog(String msg){try(FileWriter w=new FileWriter(new File(getFilesDir(),"diagnostics.txt"),true)){w.write(new Date()+" "+msg+" nativeHeap="+Debug.getNativeHeapAllocatedSize()+"\n");}catch(Exception ignored){}}
 void report(String msg){reportLog(msg);getPreferences(0).edit().putString("phase",msg).commit();runOnUiThread(()->status.setText(msg));}
 void check() throws IOException{if(cancelled)throw new IOException("已取消");}
 File download(String name,long size,long offset)throws Exception{File file=new File(getFilesDir(),name);if(file.length()==size){report("已读取缓存："+name);return file;}Exception last=null;
 for(String host:new String[]{"hf-mirror.net","huggingface.co"}){HttpURLConnection c=null;try{check();report("连接 "+host+" · "+name);URL url=new URL("https://"+host+"/sentiantai/sharp-onnx-webgpu-weights/resolve/"+revision+"/"+name);c=(HttpURLConnection)url.openConnection();c.setConnectTimeout(20000);c.setReadTimeout(30000);if(c.getResponseCode()!=200)throw new IOException("HTTP "+c.getResponseCode());long got=0,lastTime=0;File partial=new File(getFilesDir(),name+".part");try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(partial)){byte[] buf=new byte[262144];int n;while((n=in.read(buf))!=-1){check();out.write(buf,0,n);got+=n;if(got>size)throw new IOException("文件尺寸不匹配");if(System.currentTimeMillis()-lastTime>800){final long amount=offset+got;runOnUiThread(()->{progress.setIndeterminate(false);progress.setProgress((int)(amount*1000/1308098560L));status.setText("下载模型 "+amount/1048576+" / 1248 MB");});lastTime=System.currentTimeMillis();}}}if(got!=size)throw new IOException("下载不完整");if(!partial.renameTo(file))throw new IOException("无法保存缓存");return file;}catch(Exception e){last=e;if(cancelled)throw e;}finally{if(c!=null)c.disconnect();}}throw last;}
 void begin(){if(running)return;running=true;cancelled=false;int backend=mode.getSelectedItemPosition();choose.setEnabled(false);start.setEnabled(false);mode.setEnabled(false);cancel.setEnabled(true);save.setEnabled(false);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);jobs.execute(()->{try{check();download(weights,1308098560,0);File model=new File(getFilesDir(),"sharp_android_pool_v2.onnx");try(InputStream in=getAssets().open("sharp_android_pool_v2.onnx");OutputStream out=new FileOutputStream(model)){byte[] bytes=new byte[65536];int read;while((read=in.read(bytes))!=-1)out.write(bytes,0,read);}check();report("初始化原生模型 · "+(backend==0?"CPU":"NNAPI")+"，可能需要数分钟");runOnUiThread(()->progress.setIndeterminate(true));OrtEnvironment env=OrtEnvironment.getEnvironment();try(OrtSession.SessionOptions opts=new OrtSession.SessionOptions()){opts.setIntraOpNumThreads(2);opts.setInterOpNumThreads(1);opts.setMemoryPatternOptimization(false);opts.setCPUArenaAllocator(false);if(backend==1)opts.addNnapi();try(OrtSession session=env.createSession(model.getAbsolutePath(),opts)){check();Bitmap raw=BitmapFactory.decodeFile(photo.getPath());Bitmap bmp=Bitmap.createScaledBitmap(raw,1536,1536,true);if(bmp!=raw)raw.recycle();int[] pixels=new int[1536*1536];bmp.getPixels(pixels,0,1536,0,0,1536,1536);bmp.recycle();Map<String,OnnxTensor> feeds=new HashMap<>();for(Map.Entry<String,NodeInfo> e:session.getInputInfo().entrySet()){TensorInfo info=(TensorInfo)e.getValue().getInfo();boolean image=info.getShape().length==4;int len=image?1536*1536*3:1;ByteBuffer buf=ByteBuffer.allocateDirect(len*(info.type==OnnxJavaType.FLOAT16?2:4)).order(ByteOrder.nativeOrder());for(int i=0;i<len;i++){float val=image?((pixels[i%(1536*1536)]>>(16-8*(i/(1536*1536))))&255)/255f:(float)(30*Math.hypot(imageWidth,imageHeight)/Math.hypot(36,24)/imageWidth);if(info.type==OnnxJavaType.FLOAT16)buf.putShort(toHalf(val));else buf.putFloat(val);}buf.rewind();feeds.put(e.getKey(),OnnxTensor.createTensor(env,buf,image?new long[]{1,3,1536,1536}:new long[]{1},info.type));}pixels=null;check();report("正在本机推理 · 请保持前台");try(OrtSession.RunOptions ro=new OrtSession.RunOptions()){activeRun=ro;try(OrtSession.Result outputs=session.run(feeds,ro)){check();report("生成完成，正在打包记忆");result=MemoryWriter.write(getFilesDir(),photo,outputs,imageWidth,imageHeight);}}finally{activeRun=null;for(OnnxTensor t:feeds.values())t.close();}}}report("完成！可保存 .still，在记忆盒子网页打开。");getPreferences(0).edit().remove("phase").apply();runOnUiThread(()->save.setEnabled(true));}catch(Throwable e){report("未完成："+e.getClass().getSimpleName()+" · "+e.getMessage()+"\n请导出诊断日志。CPU 与系统加速的算子支持不同，可更换模式测试。");}finally{activeRun=null;running=false;runOnUiThread(()->{choose.setEnabled(true);start.setEnabled(photo!=null);mode.setEnabled(true);cancel.setEnabled(false);progress.setIndeterminate(false);getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);});}});}
 static short toHalf(float value){int bits=Float.floatToIntBits(value),s=(bits>>>16)&32768,e=((bits>>>23)&255)-112,m=bits&8388607;return(short)(e<=0?(e< -10?s:s|(((m|8388608)>>(1-e))+4096>>13)):e>=31?s|31744:s|(e<<10)+(m+4096>>13));}
}
